CREATE TABLE `blog_entries` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) DEFAULT NULL,
  `apple_news_article_id` char(36) DEFAULT NULL,
  `status` char(9) DEFAULT NULL,
  `basename` varchar(100) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `body` longtext,
  `excerpt` text,
  `type` varchar(100) DEFAULT NULL,
  `published` datetime DEFAULT NULL,
  `published_to_apple_news` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `has_pages` tinyint(1) DEFAULT '0',
  `has_extended` tinyint(1) DEFAULT '0',
  `pages` int(11) NOT NULL DEFAULT '1',
  `version` int(10) unsigned NOT NULL,
  `more_text` varchar(100) DEFAULT NULL,
  `redirect_to_url` varchar(400) DEFAULT NULL,
  `comments_version` int(1) DEFAULT '3',
  `social_url` varchar(120) DEFAULT NULL,
  `breaking_news` int(1) unsigned DEFAULT '0',
  `last_modified_user_id` int(10) unsigned DEFAULT NULL,
  `hero_shorter_title` varchar(100) DEFAULT NULL,
  `original_published` datetime DEFAULT NULL,
  `site_id` char(2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  KEY `published` (`published`),
  KEY `IDX_C10E0E469C91CAD5` (`last_modified_user_id`),
  KEY `uuid_idx` (`uuid`),
  KEY `basename` (`basename`),
  KEY `idx_blog_entries_site_id` (`site_id`),
  KEY `idx_blog_entries_title` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=113424 DEFAULT CHARSET=utf8;

 CREATE TABLE IF NOT EXISTS `blog_contributors` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `slug` varchar(30) DEFAULT NULL,
                `user_id` int(11) unsigned DEFAULT NULL,
                `display_name` varchar(400) DEFAULT NULL,
                `bio` text,
                `image_id` int(11) unsigned DEFAULT NULL,
                `redirect_url` varchar(255) DEFAULT NULL,
                `position` varchar(400) DEFAULT NULL,
                `start_date` varchar(255) DEFAULT NULL,
                `twitter` varchar(255) DEFAULT NULL,
                `email` varchar(255) DEFAULT NULL,
                `favorite_entry_id` int(11) unsigned DEFAULT NULL,
                `website` varchar(255) DEFAULT NULL,
                `google_profile_url` varchar(400) DEFAULT NULL,
                `instagram` varchar(225) DEFAULT NULL,
                `pinterest` varchar(225) DEFAULT NULL,
                `type` varchar(50) DEFAULT NULL,
                `in_page_bio` text,
                `include_in_page_bio` int(1) DEFAULT '0',
                `deleted` datetime DEFAULT NULL,
                `collection_id` int(11) DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `slug` (`slug`),
                UNIQUE KEY `UNIQ_280E8DE5A76ED395` (`user_id`),
                KEY `blog_contributor_image_id` (`image_id`),
                KEY `user_id` (`user_id`),
                KEY `favorite_entry_id` (`favorite_entry_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `blog_categories` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `name` varchar(100) NOT NULL,
                `slug` varchar(100) NOT NULL,
                `fullpath` varchar(255) DEFAULT NULL,
                `parent_id` int(11) unsigned DEFAULT NULL,
                `is_active` tinyint(1) DEFAULT '1',
                `display_order` int(10) unsigned NOT NULL DEFAULT '0',
                `is_root` tinyint(1) DEFAULT '0',
                `is_dynamic` tinyint(1) DEFAULT '0',
                `type` char(6) DEFAULT NULL,
                `is_visible` tinyint(1) DEFAULT '1',
                `admin_is_visible_targeting_tool` tinyint(1) NOT NULL DEFAULT '1',
                `admin_is_visible_mass_tagging` tinyint(1) NOT NULL DEFAULT '1',
                `admin_is_visible_entry_admin` tinyint(1) NOT NULL DEFAULT '1',
                `layout` varchar(30) DEFAULT NULL,
                `module_title` varchar(100) DEFAULT NULL,
                `display_order_mobile` int(10) unsigned NOT NULL DEFAULT '1023',
                PRIMARY KEY (`id`),
                UNIQUE KEY `parent_id` (`parent_id`,`slug`),
                KEY `fullpath` (`fullpath`),
                CONSTRAINT `blog_categories_parent` FOREIGN KEY (`parent_id`) REFERENCES `blog_categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `blog_assets` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `type` varchar(32) DEFAULT NULL,
                `title` varchar(255) DEFAULT NULL,
                `description` text,
                `tags` varchar(100) DEFAULT NULL,
                `type_id` int(11) unsigned DEFAULT NULL,
                `clicktracker` text,
                `impressiontracker` text,
                `meta_title` varchar(255) DEFAULT NULL,
                `meta_desc` text,
                `no_pin_it` tinyint(1) NOT NULL DEFAULT '0',
                `alignment` char(6) NOT NULL,
                `credit` text,
                `is_editable` tinyint(1) NOT NULL DEFAULT '1',
                `no_facebook` tinyint(1) NOT NULL DEFAULT '0',
                PRIMARY KEY (`id`),
                KEY `IDX_EC9ED84FC54C8C93` (`type_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `blog_entry_assets` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `entry_id` int(11) unsigned DEFAULT NULL,
                `asset_id` int(11) unsigned DEFAULT NULL,
                `display_order` int(11) NOT NULL DEFAULT '0',
                `type` varchar(25) DEFAULT NULL,
                `is_active` tinyint(1) DEFAULT '1',
                `crop_x` int(11) DEFAULT NULL,
                `crop_y` int(11) DEFAULT NULL,
                `crop_w` int(11) DEFAULT NULL,
                `crop_h` int(11) DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `entry_id` (`entry_id`,`asset_id`),
                KEY `asset_id` (`asset_id`),
                KEY `type` (`type`),
                KEY `entry_id_is_active_type` (`entry_id`,`is_active`,`type`),
                CONSTRAINT `blog_entry_assets_ibfk_1` FOREIGN KEY (`entry_id`) REFERENCES `blog_entries` (`id`),
                CONSTRAINT `blog_entry_assets_ibfk_2` FOREIGN KEY (`asset_id`) REFERENCES `blog_assets` (`id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `blog_tags` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `tag` varchar(100) DEFAULT NULL,
                `slug` varchar(100) DEFAULT NULL,
                `category_id` int(11) unsigned DEFAULT NULL,
                `name` varchar(100) DEFAULT NULL,
                `type` varchar(20) NOT NULL,
                `hidden` tinyint(1) DEFAULT '0',
                PRIMARY KEY (`id`),
                KEY `tag` (`tag`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8;